//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tape
{
    [Serializable]
    public class SimPredRequest : Message
    {
        public const string k_RosMessageName = "tape/SimPred";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseArrayMsg gripper_poses;
        public Std.Float32MultiArrayMsg gripper_states;

        public SimPredRequest()
        {
            this.gripper_poses = new Geometry.PoseArrayMsg();
            this.gripper_states = new Std.Float32MultiArrayMsg();
        }

        public SimPredRequest(Geometry.PoseArrayMsg gripper_poses, Std.Float32MultiArrayMsg gripper_states)
        {
            this.gripper_poses = gripper_poses;
            this.gripper_states = gripper_states;
        }

        public static SimPredRequest Deserialize(MessageDeserializer deserializer) => new SimPredRequest(deserializer);

        private SimPredRequest(MessageDeserializer deserializer)
        {
            this.gripper_poses = Geometry.PoseArrayMsg.Deserialize(deserializer);
            this.gripper_states = Std.Float32MultiArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gripper_poses);
            serializer.Write(this.gripper_states);
        }

        public override string ToString()
        {
            return "SimPredRequest: " +
            "\ngripper_poses: " + gripper_poses.ToString() +
            "\ngripper_states: " + gripper_states.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
