//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tape
{
    [Serializable]
    public class SimResetResponse : Message
    {
        public const string k_RosMessageName = "tape/SimReset";
        public override string RosMessageName => k_RosMessageName;

        public Std.BoolMsg success;

        public SimResetResponse()
        {
            this.success = new Std.BoolMsg();
        }

        public SimResetResponse(Std.BoolMsg success)
        {
            this.success = success;
        }

        public static SimResetResponse Deserialize(MessageDeserializer deserializer) => new SimResetResponse(deserializer);

        private SimResetResponse(MessageDeserializer deserializer)
        {
            this.success = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SimResetResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
