//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tsl
{
    [Serializable]
    public class SimAdjustRequest : Message
    {
        public const string k_RosMessageName = "tsl/SimAdjust";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseArrayMsg states_est;

        public SimAdjustRequest()
        {
            this.states_est = new Geometry.PoseArrayMsg();
        }

        public SimAdjustRequest(Geometry.PoseArrayMsg states_est)
        {
            this.states_est = states_est;
        }

        public static SimAdjustRequest Deserialize(MessageDeserializer deserializer) => new SimAdjustRequest(deserializer);

        private SimAdjustRequest(MessageDeserializer deserializer)
        {
            this.states_est = Geometry.PoseArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.states_est);
        }

        public override string ToString()
        {
            return "SimAdjustRequest: " +
            "\nstates_est: " + states_est.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
