//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tsl
{
    [Serializable]
    public class SimPredResponse : Message
    {
        public const string k_RosMessageName = "tsl/SimPred";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseArrayMsg states_pred;

        public SimPredResponse()
        {
            this.states_pred = new Geometry.PoseArrayMsg();
        }

        public SimPredResponse(Geometry.PoseArrayMsg states_pred)
        {
            this.states_pred = states_pred;
        }

        public static SimPredResponse Deserialize(MessageDeserializer deserializer) => new SimPredResponse(deserializer);

        private SimPredResponse(MessageDeserializer deserializer)
        {
            this.states_pred = Geometry.PoseArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.states_pred);
        }

        public override string ToString()
        {
            return "SimPredResponse: " +
            "\nstates_pred: " + states_pred.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
