//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tsl
{
    [Serializable]
    public class SimResetRequest : Message
    {
        public const string k_RosMessageName = "tsl/SimReset";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseArrayMsg states_est;
        public Std.Float32Msg rope_length;
        public Std.Float32Msg rope_radius;
        public Geometry.PoseArrayMsg eyelet_poses;
        public Geometry.PoseArrayMsg gripper_poses;
        public Std.Float32MultiArrayMsg gripper_states;
        public Geometry.TransformMsg cam2rob;

        public SimResetRequest()
        {
            this.states_est = new Geometry.PoseArrayMsg();
            this.rope_length = new Std.Float32Msg();
            this.rope_radius = new Std.Float32Msg();
            this.eyelet_poses = new Geometry.PoseArrayMsg();
            this.gripper_poses = new Geometry.PoseArrayMsg();
            this.gripper_states = new Std.Float32MultiArrayMsg();
            this.cam2rob = new Geometry.TransformMsg();
        }

        public SimResetRequest(Geometry.PoseArrayMsg states_est, Std.Float32Msg rope_length, Std.Float32Msg rope_radius, Geometry.PoseArrayMsg eyelet_poses, Geometry.PoseArrayMsg gripper_poses, Std.Float32MultiArrayMsg gripper_states, Geometry.TransformMsg cam2rob)
        {
            this.states_est = states_est;
            this.rope_length = rope_length;
            this.rope_radius = rope_radius;
            this.eyelet_poses = eyelet_poses;
            this.gripper_poses = gripper_poses;
            this.gripper_states = gripper_states;
            this.cam2rob = cam2rob;
        }

        public static SimResetRequest Deserialize(MessageDeserializer deserializer) => new SimResetRequest(deserializer);

        private SimResetRequest(MessageDeserializer deserializer)
        {
            this.states_est = Geometry.PoseArrayMsg.Deserialize(deserializer);
            this.rope_length = Std.Float32Msg.Deserialize(deserializer);
            this.rope_radius = Std.Float32Msg.Deserialize(deserializer);
            this.eyelet_poses = Geometry.PoseArrayMsg.Deserialize(deserializer);
            this.gripper_poses = Geometry.PoseArrayMsg.Deserialize(deserializer);
            this.gripper_states = Std.Float32MultiArrayMsg.Deserialize(deserializer);
            this.cam2rob = Geometry.TransformMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.states_est);
            serializer.Write(this.rope_length);
            serializer.Write(this.rope_radius);
            serializer.Write(this.eyelet_poses);
            serializer.Write(this.gripper_poses);
            serializer.Write(this.gripper_states);
            serializer.Write(this.cam2rob);
        }

        public override string ToString()
        {
            return "SimResetRequest: " +
            "\nstates_est: " + states_est.ToString() +
            "\nrope_length: " + rope_length.ToString() +
            "\nrope_radius: " + rope_radius.ToString() +
            "\neyelet_poses: " + eyelet_poses.ToString() +
            "\ngripper_poses: " + gripper_poses.ToString() +
            "\ngripper_states: " + gripper_states.ToString() +
            "\ncam2rob: " + cam2rob.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
